/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     21/08/2022 12:30:38                          */
/*==============================================================*/

/*==============================================================*/
/* Table: ARTICULO                                              */
/*==============================================================*/
create table ARTICULO 
(
   CODIGO_ART           INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   NOMBRE_ART           VARCHAR2(128),
   PRECIO_ART           VARCHAR2(8),
   STOCK_ART            INTEGER,
   constraint PK_ARTICULO primary key (CODIGO_ART)
);

/*==============================================================*/
/* Table: CABECERA_FACTURA                                      */
/*==============================================================*/
create table CABECERA_FACTURA 
(
   NUMERO_CABECERA_FACT_CXC INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CODIGO_CLI           INTEGER,
   CODIGO_CIU           INTEGER              not null,
   FECHA_CABECERA_FACTU DATE,
   VALOR_CABECERA_FACU  VARCHAR2(16),
   constraint PK_CABECERA_FACTURA primary key (NUMERO_CABECERA_FACT_CXC)
);

/*==============================================================*/
/* Index: PAGA_FK                                               */
/*==============================================================*/
create index PAGA_FK on CABECERA_FACTURA (
   CODIGO_CLI ASC
);

/*==============================================================*/
/* Index: CIUDAD_CLIENTE_FK                                     */
/*==============================================================*/
create index CIUDAD_CLIENTE_FK on CABECERA_FACTURA (
   CODIGO_CIU ASC
);

/*==============================================================*/
/* Table: CABE_C_INVENTARIO                                     */
/*==============================================================*/
create table CABE_C_INVENTARIO 
(
   NUMERO_CABE_INVEN    INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CODIGO_TMOV          INTEGER              not null,
   FECHA_CABE_INVEN     DATE,
   constraint PK_CABE_C_INVENTARIO primary key (NUMERO_CABE_INVEN)
);

/*==============================================================*/
/* Index: CABINVEN_TMOVI_FK                                     */
/*==============================================================*/
create index CABINVEN_TMOVI_FK on CABE_C_INVENTARIO (
   CODIGO_TMOV ASC
);

/*==============================================================*/
/* Table: CIUDAD                                                */
/*==============================================================*/
create table CIUDAD 
(
   CODIGO_CIU           INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   NOMBRE_CIU           VARCHAR2(128),
   constraint PK_CIUDAD primary key (CODIGO_CIU)
);

/*==============================================================*/
/* Table: CLIENTE                                               */
/*==============================================================*/
create table CLIENTE 
(
   CODIGO_CLI           INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   RUC_CLI              VARCHAR2(13),
   NOM_CLI              VARCHAR2(128),
   DIR_CLI              VARCHAR2(1258),
   constraint PK_CLIENTE primary key (CODIGO_CLI)
);

/*==============================================================*/
/* Table: COBRADOR                                              */
/*==============================================================*/
create table COBRADOR 
(
   CODIGO_COB           INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   NOM_COB              VARCHAR2(128),
   DIR_COB              VARCHAR2(128),
   CEDULA_COB           VARCHAR2(10),
   constraint PK_COBRADOR primary key (CODIGO_COB)
);

/*==============================================================*/
/* Table: DC_FACTURA                                            */
/*==============================================================*/
create table DC_FACTURA 
(
   NUMERO_CABECERA_FACT_CXC INTEGER              not null,
   CODIGO_ART           INTEGER              not null,
   CODIGO_DC_FACTURA    INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CANTIDAD_DC_FACTURA  VARCHAR2(16),
   PRECIO_DC_FACTURA    VARCHAR2(16),
   constraint PK_DC_FACTURA primary key (NUMERO_CABECERA_FACT_CXC, CODIGO_ART, CODIGO_DC_FACTURA)
);

/*==============================================================*/
/* Index: DC_FACTURA2_FK                                        */
/*==============================================================*/
create index DC_FACTURA2_FK on DC_FACTURA (
   CODIGO_ART ASC
);

/*==============================================================*/
/* Table: DC_INVENTARIO                                         */
/*==============================================================*/
create table DC_INVENTARIO 
(
   CODIGO_ART           INTEGER              not null,
   NUMERO_CABE_INVEN    INTEGER              not null,
   CODIGO_DC_INVENTARIO INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CANTIDAD_DC_INVENTARIO VARCHAR2(16),
   PRECIO_DC_INVENTARIO CHAR(16),
   constraint PK_DC_INVENTARIO primary key (CODIGO_ART, NUMERO_CABE_INVEN, CODIGO_DC_INVENTARIO)
);

/*==============================================================*/
/* Index: DC_INVENTARIO2_FK                                     */
/*==============================================================*/
create index DC_INVENTARIO2_FK on DC_INVENTARIO (
   NUMERO_CABE_INVEN ASC
);

/*==============================================================*/
/* Table: DETALLES_PAGOS_CXC                                    */
/*==============================================================*/
create table DETALLES_PAGOS_CXC 
(
   CODIGO_PAGOS_CXC     INTEGER              GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CODIGO_FP            INTEGER              not null,
   CODIGO_COB           INTEGER              not null,
   NUMERO_CABECERA_FACT_CXC INTEGER              not null,
   FECHA_DETALLE_PAGOS_CXC DATE,
   VALOR_DETALLE_PAGOS_CXC VARCHAR2(32),
   constraint PK_DETALLES_PAGOS_CXC primary key (CODIGO_PAGOS_CXC)
);

/*==============================================================*/
/* Index: CABECERAFACTURA_COBRADOR_FK                           */
/*==============================================================*/
create index CABECERAFACTURA_COBRADOR_FK on DETALLES_PAGOS_CXC (
   CODIGO_COB ASC
);

/*==============================================================*/
/* Index: DETALLE_FACTURA_CXC_FK                                */
/*==============================================================*/
create index DETALLE_FACTURA_CXC_FK on DETALLES_PAGOS_CXC (
   NUMERO_CABECERA_FACT_CXC ASC
);

/*==============================================================*/
/* Index: DETALLE_FP_CXC_FK                                     */
/*==============================================================*/
create index DETALLE_FP_CXC_FK on DETALLES_PAGOS_CXC (
   CODIGO_FP ASC
);

/*==============================================================*/
/* Table: FORMAPAGO                                             */
/*==============================================================*/
create table FORMAPAGO 
(
   CODIGO_FP            INTEGER              not null,
   NOM_FP               VARCHAR2(128),
   constraint PK_FORMAPAGO primary key (CODIGO_FP)
);

/*==============================================================*/
/* Table: TIPOMOVIMIENTO                                        */
/*==============================================================*/
create table TIPOMOVIMIENTO 
(
   CODIGO_TMOV          INTEGER              not null,
   NOMBRE_TMOV          VARCHAR2(128),
   SIGNO_TMOV           VARCHAR2(128),
   constraint PK_TIPOMOVIMIENTO primary key (CODIGO_TMOV)
);

alter table CABECERA_FACTURA
   add constraint FK_CABECERA_CIUDAD_CL_CIUDAD foreign key (CODIGO_CIU)
      references CIUDAD (CODIGO_CIU);

alter table CABECERA_FACTURA
   add constraint FK_CABECERA_PAGA_CLIENTE foreign key (CODIGO_CLI)
      references CLIENTE (CODIGO_CLI);

alter table CABE_C_INVENTARIO
   add constraint FK_CABE_C_I_CABINVEN__TIPOMOVI foreign key (CODIGO_TMOV)
      references TIPOMOVIMIENTO (CODIGO_TMOV);

alter table DC_FACTURA
   add constraint FK_DC_FACTU_DC_FACTUR_CABECERA foreign key (NUMERO_CABECERA_FACT_CXC)
      references CABECERA_FACTURA (NUMERO_CABECERA_FACT_CXC);

alter table DC_FACTURA
   add constraint FK_DC_FACTU_DC_FACTUR_ARTICULO foreign key (CODIGO_ART)
      references ARTICULO (CODIGO_ART);

alter table DC_INVENTARIO
   add constraint FK_DC_INVEN_DC_INVENT_ARTICULO foreign key (CODIGO_ART)
      references ARTICULO (CODIGO_ART);

alter table DC_INVENTARIO
   add constraint FK_DC_INVEN_DC_INVENT_CABE_C_I foreign key (NUMERO_CABE_INVEN)
      references CABE_C_INVENTARIO (NUMERO_CABE_INVEN);

alter table DETALLES_PAGOS_CXC
   add constraint FK_DETALLES_CABECERAF_COBRADOR foreign key (CODIGO_COB)
      references COBRADOR (CODIGO_COB);

alter table DETALLES_PAGOS_CXC
   add constraint FK_DETALLES_DETALLE_F_CABECERA foreign key (NUMERO_CABECERA_FACT_CXC)
      references CABECERA_FACTURA (NUMERO_CABECERA_FACT_CXC);

alter table DETALLES_PAGOS_CXC
   add constraint FK_DETALLES_DETALLE_F_FORMAPAG foreign key (CODIGO_FP)
      references FORMAPAGO (CODIGO_FP);

